name: flutter_base_start
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1



dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  
  #state management
  flutter_bloc: ^9.1.1

  #dependency injection
  get_it: ^8.2.0

  #navigation 
  go_router: ^16.2.4

  #logging
  logger: ^2.6.1

  #local storage
  shared_preferences: ^2.5.3

  #firebase services
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3
  meta: ^1.16.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0
  very_good_analysis: ^9.0.0


flutter:
  
  uses-material-design: true

